years:
  - 2024
  - 2023
  - 2022
  - 2021
  - 2020
sources:
  2024: "https://irdai.gov.in/sites/default/files/2025-02/Handbook_on_Indian_Insurance_Statistics_2023_24.zip"
  2023: "https://irdai.gov.in/sites/default/files/2024-02/Handbook_on_Indian_Insurance_Statistics_2022_23.zip"
  2022: "https://irdai.gov.in/sites/default/files/2023-02/Handbook_on_Indian_Insurance_Statistics_2021_22.zip"
  2021: "https://irdai.gov.in/sites/default/files/2022-02/Handbook_on_Indian_Insurance_Statistics_2020_21.zip"
  2020: "https://irdai.gov.in/sites/default/files/2021-02/Handbook_on_Indian_Insurance_Statistics_2019_20.zip"
